---
- name: Install Apache2 integration
  apt: name={{ item }} state=installed
  with_items:
    - libapache2-mod-php5
  become: true
  notify:
  - Restart apache2

- name: Put an apache2 config file
  action: copy src=apache2.dir.conf dest=/etc/apache2/mods-available/dir.conf owner=root group=root mode=0644
  become: true
  notify:
  - Restart apache2

- name: Enable mod_rewrite
  command: a2enmod rewrite
  become: true
  notify:
  - Restart apache2
