---
- debug: msg="www_user = {{www_user}}"
- debug: msg="www_group = {{www_group}}"
- debug: msg="integrate_with_apache = {{integrate_with_apache}}"
- debug: msg="integrate_with_mysql = {{integrate_with_mysql}}"

- include: php.yml

- include: apache-integration.yml
  when: integrate_with_apache

- include: mysql-integration.yml
  when: integrate_with_mysql
