---
- debug: msg="www_user = {{www_user}}"
- debug: msg="www_group = {{www_group}}"
- debug: msg="integrate_with_apache = {{integrate_with_apache}}"
- debug: msg="integrate_with_mysql = {{integrate_with_mysql}}"

- name: Include php.yml
  include: php.yml

- name: Conditionally include apache-integration.yml
  include: apache-integration.yml
  when: integrate_with_apache

- name: Conditionally include mysql-integration.yml
  include: mysql-integration.yml
  when: integrate_with_mysql
